### ISSUE TITLE
[TF2] Can't disable Eureka Effect

### ISSUE THREAD

**Issue by Code-Lyoko0** [worMatty/deathrun_toolkit#13]
This is my current restrictions.cfg, I am currently trying to disable the Eureka Effect and can't seem to do it. even though it seems that everything is right.

// When a player receives a weapon, the plugin checks if its Item Definition Index is here
// If it is, it either applies attributes or requests a replacement

"restrictions"
{
	"1179"	// Thermal Thruster
	{
		"attributes"
		{
			"1"
			{
				"name"		"item_meter_charge_rate"
				"value"		"0.0"	// Only two charges
			}
		}
	}
	
	"812"	// Cleaver - Can be thrown through walls
	{
		"replace"	"1"
	}
	
	"833"	// Cleaver - Can be thrown through walls
	{
		"replace"	"1"
	}

	"589"	// Eureka Effect
	{
		"replace"	"1"
	}

}

Is there anything I am missing here or did I mess something up?

**Comment by worMatty** [comment]
No that looks fine to me. It's working my end. 

```
// When a player receives a weapon, the plugin checks if its Item Definition Index is here
// If it is, it either applies attributes or requests a replacement

"restrictions"
{
	// Pyro

	"1179"	// Thermal Thruster
	{
		"attributes"
		{
			"1"
			{
				"name"		"item_meter_charge_rate"
				"value"		"0.0"	// Only two charges
			}
		}
	}
	
	
	// Scout
	
	"812"	// Cleaver - Can be thrown through walls
	{
		"replace"	"1"
	}
	
	"833"	// Cleaver - Can be thrown through walls
	{
		"replace"	"1"
	}
	
	
	// Engi
	
	"589"	// Eureka Effect
	{
		"replace"	"1"
	}
}
```
Do you also have `replacements.cfg` in configs/dtk?
