### ISSUE TITLE
trigger_hurt??? how do i disable this????

### ISSUE THREAD

**Issue by ADAR102** [worMatty/deathrun_toolkit#36]
"You were killed by a trigger_hurt (afk_killah)"

whenever i spawn in even when players are not afk they still die repetitively. i only installed deathrun_toolkit and i am unsure if i have to install another deathrun plugin.

**Comment by worMatty** [comment]
Hi, there.

DTK tells you the type and name of the map entity that killed you. It sounds like you are being killed by the map's AFK spawn killer.

**Comment by ADAR102** [comment]
i was on this map https://steamcommunity.com/sharedfiles/filedetails/?id=845183322&searchtext=deathrun

**Comment by worMatty** [comment]
Working fine for me mate. Pop into our [Discord](https://steamcommunity.com/groups/death_experiments) if you like and tell us more about what you're doing.
